### ISSUE TITLE
Flat file input/output for LocOO3D doesn't like LDDATE field

### ISSUE THREAD

**Issue by mbegnaud** [sandialabs/Salsa3DSoftware#5]
The flat file input/output for LocOO3D will throw an error if one of the header fields is LDDATE like what is in legacy CSS3.0 tables and NNSA KB Core database tables.

**Comment by bjlawry** [comment]
Hey Mike, can you include a copy of the stack trace you get when "LDDATE" is a header field?

**Comment by mbegnaud** [comment]
java.io.IOException: Error: input column name "LDDATE" is not a valid name ...
            at gov.sandia.gnem.dbtabledefs.Columns.containsValidColumnNames(Columns.java:347)
            at gov.sandia.gnem.dbtabledefs.nnsa_kb_core.Origin.setNewInputColumnNames(Origin.java:621)
            at gov.sandia.gnem.dbtabledefs.nnsa_kb_core.Origin.readOrigins(Origin.java:859)
            at gov.sandia.gnem.dbtabledefs.nnsa_kb_core.Origin.readOrigins(Origin.java:901)
            at gov.sandia.gnem.dbtabledefs.nnsa_kb_core_extended.OriginExtended.readOriginExtended(OriginExtended.java:1863)
            at gov.sandia.gnem.dbtabledefs.nnsa_kb_core_extended.OriginExtended.readOriginExtended(OriginExtended.java:1848)
            at gov.sandia.gnem.dbtabledefs.nnsa_kb_core_extended.OriginExtended.readBufferedReaders(OriginExtended.java:2089)
            at gov.sandia.gnem.dbtabledefs.nnsa_kb_core_extended.OriginExtended.readBufferedReaders(OriginExtended.java:2059)
            at gov.sandia.gnem.dbtabledefs.nnsa_kb_core_extended.OriginExtended.readOriginExtended(OriginExtended.java:1931)
            at gov.sandia.gnem.dbtabledefs.nnsa_kb_core_extended.OriginExtended.readOriginExtended(OriginExtended.java:1906)
            at gov.sandia.gmp.locoo3d.io.KBFileInput.<init>(KBFileInput.java:76)
            at gov.sandia.gmp.locoo3d.io.LocOO_IO.createInput(LocOO_IO.java:105)
            at gov.sandia.gmp.locoo3d.io.LocOO_IO.<init>(LocOO_IO.java:71)
            at gov.sandia.gmp.locoo3d.LocOO.main(LocOO.java:375)

From: bjlawry ***@***.***>
Reply-To: sandialabs/Salsa3DSoftware ***@***.***>
Date: Thursday, May 8, 2025 at 11:48 AM
To: sandialabs/Salsa3DSoftware ***@***.***>
Cc: Michael Begnaud ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [sandialabs/Salsa3DSoftware] Flat file input/output for LocOO3D doesn't like LDDATE field (Issue #5)

[https://avatars.githubusercontent.com/u/129418530?s=20&v=4]bjlawry left a comment (sandialabs/Salsa3DSoftware#5)<https://urldefense.com/v3/__https:/github.com/sandialabs/Salsa3DSoftware/issues/5*issuecomment-2863821784__;Iw!!Bt8fGhp8LhKGRg!FUIvqyAwMvHZe_AVNtHWpUypGAMqgc3W7wZLQoTCTjFWucnCBpU8AXjfjj7U6D3BEkUQsbwWHtWeH5Mg3LgvmJLvFg$>

Hey Mike, can you include a copy of the stack trace you get when "LDDATE" is a header field?
